/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import dao.CategoryDAO;
import dao.TransactionDTO;
import dao.UserBalanceDAO;
import dao.UserDAO;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class UserDashboard extends javax.swing.JFrame {

    private List<TransactionDTO> transactionList;
    private static final String FILE_NAME_TRANSACTION = "TRANSACTION.DAT";

    private List<UserBalanceDAO> userBalanceList;
    private static final String FILE_NAME_USERBALANCE = "USERBALANCE.DAT";

    private Login login;

    private UserDAO user;

    private UserBalanceDAO userBalance;

    public UserDAO getUser() {
        return user;
    }

    public void setUser(UserDAO user) {
        this.user = user;
    }

    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public UserDashboard(UserDAO user, Login login) {
        this();
        this.user = user;
        this.login = login;
        setLbEmailText();
        LoadDataTransaction();
        LoadDataUserBalance();
        determineUserBalance();
        setUserBlanceText();
        setUserTotalPurchase();
    }

    private void LoadDataTransaction() {
        File file = new File(FILE_NAME_TRANSACTION);
        if (file.length() > 0) {
            try (FileInputStream fis = new FileInputStream(FILE_NAME_TRANSACTION); ObjectInputStream ois = new ObjectInputStream(fis)) {
                transactionList = (List<TransactionDTO>) ois.readObject();  // Đọc danh sách người dùng từ tệp
            } catch (IOException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        } else {
            transactionList = new ArrayList<>();  // Nếu tệp rỗng, khởi tạo danh sách trống
        }
    }

    private void LoadDataUserBalance() {
        File file = new File(FILE_NAME_USERBALANCE);
        if (file.length() > 0) {
            try (FileInputStream fis = new FileInputStream(FILE_NAME_USERBALANCE); ObjectInputStream ois = new ObjectInputStream(fis)) {
                userBalanceList = (List<UserBalanceDAO>) ois.readObject();  // Đọc danh sách người dùng từ tệp
            } catch (IOException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        } else {
            userBalanceList = new ArrayList<>();  // Nếu tệp rỗng, khởi tạo danh sách trống
        }
    }

    public void setLbEmailText() {
        lbUserEmail.setText(user.getEmail());
    }

    public void setUserBlanceText() {
        txtUserBalance.setText(userBalance.getBalance().toString());
    }

    public void determineUserBalance() {
        if (userBalanceList.size() > 0) {
            String tmpUserID = this.user.getUserID();
            for (UserBalanceDAO userBalanceDAO : userBalanceList) {
                if (userBalanceDAO.getUserID().equals(tmpUserID)) {
                    this.userBalance = userBalanceDAO;
                }
            }
        }
    }

    public void setUserTotalPurchase() {
        Double tmpTotal = (double) 0;
        for (TransactionDTO transactionDTO : transactionList) {
            if (transactionDTO.getUserID().equals(this.user.getUserID())) {
                tmpTotal += transactionDTO.getTotalPrice();
            }
        }
        txtTotalPurchase.setText(tmpTotal.toString());
    }

    public void setAfterPurchaseSuccess(UserBalanceDAO newUserBalanceDAO) {
        this.userBalance = newUserBalanceDAO;
        LoadDataTransaction();
        LoadDataUserBalance();
        setUserBlanceText();
        setUserTotalPurchase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbUserEmail = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbPurchase = new javax.swing.JLabel();
        lbPurchaseDetail = new javax.swing.JLabel();
        lbMyAccount = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbTotalPurchase = new javax.swing.JLabel();
        txtTotalPurchase = new javax.swing.JTextField();
        lbUserBalance = new javax.swing.JLabel();
        txtUserBalance = new javax.swing.JTextField();
        btnAddMoreBalance = new javax.swing.JButton();
        txtAddMoreBalance = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping.png"))); // NOI18N
        jLabel1.setText("ONLINE SHOPPING");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jLabel2.setText("Logout");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        lbUserEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbUserEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        lbUserEmail.setText("user@gmail.com");

        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 486, Short.MAX_VALUE)
                .addComponent(lbUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lbUserEmail))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jPanel3.setBackground(new java.awt.Color(153, 0, 153));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // NOI18N
        jLabel4.setText("DASHBOARD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        lbPurchase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPurchase.setForeground(new java.awt.Color(255, 255, 255));
        lbPurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping.png"))); // NOI18N
        lbPurchase.setText("Purchase");
        lbPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPurchaseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPurchaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPurchaseMouseExited(evt);
            }
        });

        lbPurchaseDetail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPurchaseDetail.setForeground(new java.awt.Color(255, 255, 255));
        lbPurchaseDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/product_light.png"))); // NOI18N
        lbPurchaseDetail.setText("Purchase Details");
        lbPurchaseDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbPurchaseDetailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPurchaseDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPurchaseDetailMouseExited(evt);
            }
        });

        lbMyAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMyAccount.setForeground(new java.awt.Color(255, 255, 255));
        lbMyAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit_supplier_light.png"))); // NOI18N
        lbMyAccount.setText("My Account");
        lbMyAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMyAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMyAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMyAccountMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMyAccount)
                    .addComponent(lbPurchaseDetail)
                    .addComponent(lbPurchase))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbPurchase)
                .addGap(50, 50, 50)
                .addComponent(lbPurchaseDetail)
                .addGap(57, 57, 57)
                .addComponent(lbMyAccount)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));

        lbTotalPurchase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTotalPurchase.setForeground(new java.awt.Color(255, 255, 255));
        lbTotalPurchase.setText("Total Purchase:");

        txtTotalPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPurchaseActionPerformed(evt);
            }
        });

        lbUserBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbUserBalance.setForeground(new java.awt.Color(255, 255, 255));
        lbUserBalance.setText("My Blance:");

        btnAddMoreBalance.setBackground(new java.awt.Color(153, 153, 153));
        btnAddMoreBalance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddMoreBalance.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMoreBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction_light.png"))); // NOI18N
        btnAddMoreBalance.setText("Add funds to account");
        btnAddMoreBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMoreBalanceActionPerformed(evt);
            }
        });

        txtAddMoreBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddMoreBalanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAddMoreBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(txtAddMoreBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUserBalance)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtUserBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(lbTotalPurchase)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTotalPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMoreBalance)
                    .addComponent(txtAddMoreBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserBalance)
                    .addComponent(txtUserBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotalPurchase)
                    .addComponent(txtTotalPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("My Statistics");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(393, 393, 393)
                                .addComponent(jLabel8)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(rootPane, "Do you want to logout now?", "Logout", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void lbMyAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMyAccountMouseClicked
        // TODO add your handling code here:
        UserAccount userAccount = new UserAccount(login, user, this);
        userAccount.setVisible(true);
    }//GEN-LAST:event_lbMyAccountMouseClicked

    private void lbPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPurchaseMouseClicked
        // TODO add your handling code here:
        Purchase purchase = new Purchase(login, user, this);
        purchase.setVisible(true);
    }//GEN-LAST:event_lbPurchaseMouseClicked

    private void lbPurchaseDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPurchaseDetailMouseClicked
        // TODO add your handling code here:
        PurchaseDetails purchaseDetails = new PurchaseDetails(login, user, this);
        purchaseDetails.setVisible(true);
    }//GEN-LAST:event_lbPurchaseDetailMouseClicked

    private void txtTotalPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalPurchaseActionPerformed

    private void btnAddMoreBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMoreBalanceActionPerformed
        // TODO add your handling code here:
        if (txtAddMoreBalance.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(rootPane, "Please add more balance first!", "Warning", 2);
        } else {
            Double tmpAddMoreBalance = Double.parseDouble(txtAddMoreBalance.getText().toString());
            for (int i = 0; i < userBalanceList.size(); i++) {
                UserBalanceDAO tmpUserBalanceDAO = userBalanceList.get(i);
                if (tmpUserBalanceDAO.getUserID().equals(this.user.getUserID())) {
                    tmpUserBalanceDAO.setBalance(tmpUserBalanceDAO.getBalance() + tmpAddMoreBalance);
                    login.setUserBalanceListDataReplace(userBalanceList);
                    JOptionPane.showMessageDialog(rootPane, "Add Balance Succeed!");
                    this.userBalance = tmpUserBalanceDAO;
                    txtAddMoreBalance.setText("");
                    this.setUserBlanceText();
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnAddMoreBalanceActionPerformed

    private void txtAddMoreBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddMoreBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddMoreBalanceActionPerformed

    private void lbPurchaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPurchaseMouseEntered
        // TODO add your handling code here:
        lbPurchase.setBackground(Color.LIGHT_GRAY); // Màu nền sáng
        lbPurchase.setOpaque(true); // Đảm bảo JLabel hiển thị màu nền
    }//GEN-LAST:event_lbPurchaseMouseEntered

    private void lbPurchaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPurchaseMouseExited
        // TODO add your handling code here:
        lbPurchase.setBackground(null); // Khôi phục màu nền mặc định
        lbPurchase.setOpaque(false); // Không hiển thị màu nền
    }//GEN-LAST:event_lbPurchaseMouseExited

    private void lbPurchaseDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPurchaseDetailMouseEntered
        // TODO add your handling code here:
        lbPurchaseDetail.setBackground(Color.LIGHT_GRAY); // Màu nền sáng
        lbPurchaseDetail.setOpaque(true); // Đảm bảo JLabel hiển thị màu nền
    }//GEN-LAST:event_lbPurchaseDetailMouseEntered

    private void lbPurchaseDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPurchaseDetailMouseExited
        // TODO add your handling code here:
        lbPurchaseDetail.setBackground(null); // Khôi phục màu nền mặc định
        lbPurchaseDetail.setOpaque(false); // Không hiển thị màu nền
    }//GEN-LAST:event_lbPurchaseDetailMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbMyAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMyAccountMouseEntered
        // TODO add your handling code here:
        lbMyAccount.setBackground(Color.LIGHT_GRAY); // Màu nền sáng
        lbMyAccount.setOpaque(true); // Đảm bảo JLabel hiển thị màu nền
    }//GEN-LAST:event_lbMyAccountMouseEntered

    private void lbMyAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMyAccountMouseExited
        // TODO add your handling code here:
        lbMyAccount.setBackground(null); // Khôi phục màu nền mặc định
        lbMyAccount.setOpaque(false); // Không hiển thị màu nền
    }//GEN-LAST:event_lbMyAccountMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMoreBalance;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbMyAccount;
    private javax.swing.JLabel lbPurchase;
    private javax.swing.JLabel lbPurchaseDetail;
    private javax.swing.JLabel lbTotalPurchase;
    private javax.swing.JLabel lbUserBalance;
    private javax.swing.JLabel lbUserEmail;
    private javax.swing.JTextField txtAddMoreBalance;
    private javax.swing.JTextField txtTotalPurchase;
    private javax.swing.JTextField txtUserBalance;
    // End of variables declaration//GEN-END:variables
}
